# List of documents with points for monographs
monographs:
  - url: https://www.bip.nauka.gov.pl/g2/oryginal/2019_01/1c2912c1f994b8d37a305fac21b8ab54.pdf
    date: 18.01.2019
    title: Komunikat Ministra Nauki i Szkolnictwa Wyższego z dnia 18 stycznia 2019 roku

  - url: https://www.bip.nauka.gov.pl/g2/oryginal/2019_12/9403b58df69c1fb6eee08a2225faf847.pdf
    date: 17.12.2019
    title: Komunikat Ministra Nauki i Szkolnictwa Wyższego z dnia 17 grudnia 2019 roku

  - url: https://www.bip.nauka.gov.pl/g2/oryginal/2020_09/1e07e3553c78f5d9ebb48c9210bc0520.pdf
    date: 29.09.2020
    title: Komunikat Ministra Nauki i Szkolnictwa Wyższego z dnia 29 września 2020 roku

# Path to directory with raw data files
data_path: ./data

# Path to SQLite file
db_file: database.db

# Path to the text index directory
text_index_path: ./text_index
